"""initial schema

Revision ID: 69a0b56289f3
Revises: 
Create Date: 2026-07-24 14:05:14.736524
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '69a0b56289f3'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=12), nullable=False),
    sa.Column('isin', sa.String(length=12), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('short_name', sa.String(length=120), nullable=True),
    sa.Column('sector', sa.String(length=80), nullable=True),
    sa.Column('country', sa.String(length=80), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('shares_outstanding', sa.BigInteger(), nullable=True),
    sa.Column('website', sa.String(length=300), nullable=True),
    sa.Column('description_fr', sa.Text(), nullable=True),
    sa.Column('description_en', sa.Text(), nullable=True),
    sa.Column('listing_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('isin')
    )
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_companies_ticker'), ['ticker'], unique=True)

    op.create_table('ingestion_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job', sa.String(length=30), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stats', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('code_version', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('licensed_entities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('country', sa.String(length=80), nullable=True),
    sa.Column('approval_number', sa.String(length=60), nullable=True),
    sa.Column('approval_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('website', sa.String(length=300), nullable=True),
    sa.Column('source_url', sa.String(length=700), nullable=True),
    sa.Column('registry_refreshed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('approval_number', name='uq_entity_approval')
    )
    with op.batch_alter_table('licensed_entities', schema=None) as batch_op:
        batch_op.create_index('ix_entity_name', ['name'], unique=False)

    op.create_table('company_metrics',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=True),
    sa.Column('last_close', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('trailing_dividend_yield', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('high_52w', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('low_52w', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('ytd_return', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('avg_daily_volume_20d', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('avg_daily_value_20d', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('company_id')
    )
    op.create_table('daily_quotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('high', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('low', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('close', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('previous_close', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('value_traded', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('ingestion_run_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ingestion_run_id'], ['ingestion_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'date', name='uq_quote_company_date')
    )
    with op.batch_alter_table('daily_quotes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_quotes_company_id'), ['company_id'], unique=False)
        batch_op.create_index('ix_quote_date', ['date'], unique=False)

    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('doc_type', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('language', sa.String(length=2), nullable=False),
    sa.Column('publication_date', sa.Date(), nullable=True),
    sa.Column('source_url', sa.String(length=700), nullable=True),
    sa.Column('storage_path', sa.String(length=700), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('mime', sa.String(length=120), nullable=True),
    sa.Column('byte_size', sa.BigInteger(), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingestion_run_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ingestion_run_id'], ['ingestion_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_hash', name='uq_doc_content_hash')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index('ix_doc_company', ['company_id'], unique=False)
        batch_op.create_index('ix_doc_type_date', ['doc_type', 'publication_date'], unique=False)

    op.create_table('index_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('index_code', sa.String(length=40), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('value', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('change_pct', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('ingestion_run_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ingestion_run_id'], ['ingestion_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('index_code', 'date', name='uq_index_code_date')
    )
    with op.batch_alter_table('index_values', schema=None) as batch_op:
        batch_op.create_index('ix_index_date', ['date'], unique=False)

    op.create_table('primary_operations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issuer_name', sa.String(length=200), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('operation_type', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('open_date', sa.Date(), nullable=True),
    sa.Column('close_date', sa.Date(), nullable=True),
    sa.Column('price_min', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('price_max', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('min_subscription', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('tranches', sa.JSON(), nullable=True),
    sa.Column('eligibility_notes_fr', sa.Text(), nullable=True),
    sa.Column('sgi_lead', sa.String(length=200), nullable=True),
    sa.Column('notice_url', sa.String(length=700), nullable=True),
    sa.Column('source_url', sa.String(length=700), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('corporate_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('description_fr', sa.Text(), nullable=True),
    sa.Column('source_url', sa.String(length=700), nullable=True),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('corporate_events', schema=None) as batch_op:
        batch_op.create_index('ix_event_date', ['event_date'], unique=False)

    op.create_table('dividends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('amount_gross', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('amount_net', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('announcement_date', sa.Date(), nullable=True),
    sa.Column('ex_date', sa.Date(), nullable=True),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('agm_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('ingestion_run_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ingestion_run_id'], ['ingestion_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'fiscal_year', 'ex_date', name='uq_div_company_year_ex')
    )
    with op.batch_alter_table('dividends', schema=None) as batch_op:
        batch_op.create_index('ix_div_company', ['company_id'], unique=False)
        batch_op.create_index('ix_div_ex_date', ['ex_date'], unique=False)

    op.create_table('market_recaps',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('composite_value', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('composite_change_pct', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('advancers', sa.Integer(), nullable=True),
    sa.Column('decliners', sa.Integer(), nullable=True),
    sa.Column('unchanged', sa.Integer(), nullable=True),
    sa.Column('top_movers', sa.JSON(), nullable=True),
    sa.Column('most_active', sa.JSON(), nullable=True),
    sa.Column('boc_document_id', sa.Integer(), nullable=True),
    sa.Column('quality_passed', sa.Boolean(), nullable=False),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['boc_document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_table('newsletter_signups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('locale', sa.String(length=2), nullable=False),
    sa.Column('profile', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('operation_id', sa.Integer(), nullable=True),
    sa.Column('provider_id', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['operation_id'], ['primary_operations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', 'operation_id', name='uq_signup_email_operation')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('newsletter_signups')
    op.drop_table('market_recaps')
    with op.batch_alter_table('dividends', schema=None) as batch_op:
        batch_op.drop_index('ix_div_ex_date')
        batch_op.drop_index('ix_div_company')

    op.drop_table('dividends')
    with op.batch_alter_table('corporate_events', schema=None) as batch_op:
        batch_op.drop_index('ix_event_date')

    op.drop_table('corporate_events')
    op.drop_table('primary_operations')
    with op.batch_alter_table('index_values', schema=None) as batch_op:
        batch_op.drop_index('ix_index_date')

    op.drop_table('index_values')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index('ix_doc_type_date')
        batch_op.drop_index('ix_doc_company')

    op.drop_table('documents')
    with op.batch_alter_table('daily_quotes', schema=None) as batch_op:
        batch_op.drop_index('ix_quote_date')
        batch_op.drop_index(batch_op.f('ix_daily_quotes_company_id'))

    op.drop_table('daily_quotes')
    op.drop_table('company_metrics')
    with op.batch_alter_table('licensed_entities', schema=None) as batch_op:
        batch_op.drop_index('ix_entity_name')

    op.drop_table('licensed_entities')
    op.drop_table('ingestion_runs')
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_companies_ticker'))

    op.drop_table('companies')
    # ### end Alembic commands ###
